Training/Corridorr/config/routes.rb
Rails.application.routes.draw do
  # get 'launch/new'

  get 'apps/new'

  get '/apps/new' 

   post 'launch/show' => 'launch#show'

	get "log_out" => "sessions#destroy", :as => "log_out"

  get 'log_in' => 'sessions#new' , :as => 'log_in'

  get "sign_up" => "users#new", :as => "sign_up"


 # post 'launch/create'   => 'launch#create'
  

 root :to => 'users#index'


resources :users
resources :sessions
resources :apps
resources :launch 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Training/Corridorr/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

Training/Corridorr/app/models/launch.rb
class Launch < ApplicationRecord
	 # attr_accessor :Request_for, :from, :to, :Reason

	 belongs_to :user
	LAUNCH_LIST = ["work from home","Maternity leave","Adoption leave", "other"]
end

Training/Corridorr/app/models/user.rb
class User < ApplicationRecord

  has_many :launches
 attr_accessor :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
 def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

Training/Corridorr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end




end

Training/Corridorr/app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def new
  end
end

Training/Corridorr/app/controllers/launch_controller.rb
class LaunchController < ApplicationController
	 
  
   def index
   
  end

  	def show
     @launches = Launch.all
  end

  # GET /users/new
  def new
   @launch = Launch.new
  end

  # GET /users/1/edit
  def edit
  end

 
  # POST /users
  # POST /users.json
  def create
if  @launch = Launch.new(launch_params)
 
    respond_to do |format|
      @launch.save
        format.html { redirect_to launch_url , notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: launch_url }
      # else
      #   format.html { render :new }
      #   format.json { render json:   launch_url .errors, status: :unprocessable_entity }
      end
    end
end
 
  private
 private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @launch = Launch.find(params[:id])
    end

    

def launch_params
    params.require(:launch).permit(:Request_for, :from, :to, :Reason)
  end


 end

Training/Corridorr/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end



   def create
     user = User.authenticate(params[:username], params[:password])
      # Save the user ID in the session so it can be used in
      # subsequent requests
      if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert="Invalid email and password"
      render "new"
    end
  end


def destroy
  session[:user_id] = nil
  redirect_to root_url

end
end

Training/Corridorr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end 

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to new_user_url, :notice => "Signed up!"
  else
    render "new"
  end
end


    # Use callbacks to share common setup or constraints between actions.
    # def set_user
    #   @user = User.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

Training/Corridorr/app/helpers/application_helper.rb
module ApplicationHelper
end

Training/Corridorr/app/helpers/apps_helper.rb
module AppsHelper
end

Training/Corridorr/app/helpers/launch_helper.rb
module LaunchHelper
end

Training/Corridorr/app/helpers/sessions_helper.rb
module SessionsHelper
end

Training/Corridorr/app/helpers/users_helper.rb
module UsersHelper
end

Training/Corridorr/app/views/apps/new.html.erb
<!-- <h1>Apps#new</h1> -->
<div class="card-body">
	<div class="leave">
<div class="vc_col-md-3 app-tile wpb_column column_container col padding-3 color-light"  " data-animation="" data-delay="">
		<div class="wpb_wrapper">
			<h1 class="headline font-inherit fontsize-xxl fontweight-inherit lh-inherit align-left transform-inherit " style="margin: 30px 0 20px 0;">Leave Management</h1>
	<div class="wpb_text_column wpb_content_element " >
		<div class="wpb_wrapper">
			<p>App to plan your time-off and keep all relevant stakeholders informed</p>

		</div>
	</div>
</div>
<a href="\launch\new" target="_self" class="button color-8 small " style="border-radius: 2px;">Launch</a><div class="spacer" style="height: 40px;"></div>

</div>
</div>

Training/Corridorr/app/views/launch/index.html.erb
index.html.erb

Training/Corridorr/app/views/launch/new.html.erb
<!-- <h1>Launch#new</h1> -->

<%=form_for :launch, url: '/launches/show' do |form| %>
 



  <div class="field">
    <%= form.label :Request_for %>
    <%= form.select(:Request_for, Launch::LAUNCH_LIST) %>
  </div>

<div class="field">
	 <%= form.label :from %>
<input max-date name='leaveDate' id="leave-date" type="date" min='2017-12-10'>
</div>
  
<div class="field">
	 <%= form.label :to%>
<input max-date name='leaveDate' id="leave-date" type="date" min='2017-12-10'>
</div>

<div class="field">
	 <%= form.label :Reason %><br/>
    <%= form.text_area :Reason %>
</div>

 <div class="actions">
    <%= form.submit "Apply", class: "btn btn-primary" %>
  </div>


<%end%>

Training/Corridorr/app/views/launch/show.html.erb
<table>
  <thead>
    <tr>
      <th>Request_for</th>
      <th>from</th>
      <th>to</th>
      <th>Reason for leaving</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @launches.each do |launch| %>
      <tr>
        <td><%= launch.Request_for %></td>
        <td><%= launch.from %></td>
        <td><%= launch.to %></td>
        <td><%= launch.Reason %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

Training/Corridorr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Corridorr</title>
    <%= csrf_meta_tags %>

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<!--   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script> -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <div class="container"> -->

 

<div class="card bg-dark text-white">
      <div class="card-header">

<div id="user_nav">
	<a href="/users/"> <img src="https://corridor.pramati.com/wp-content/uploads/2015/12/logo_corridor_ev3.png" alt="Corridor" class="logo_transparent" ></a>
	<div class="cometo">
	 <a class="We" href="">HOW WE DO IT</a>
          <!-- <a class="Apps" href="/users/#idea">APPS</a> -->
  <% if current_user %>
    <!-- Logged in as <%= current_user.email %>. -->
    <a class="Apps" href="/apps/new">APPS</a>
      <%= link_to "LOG OUT", log_out_path %>

  <% else %>
 
         <a class="Apps" href="/users/#idea">APPS</a>
          <a class="sign_up" href="/users/new">SIGN UP</a>
          <a class="login" href="/sessions/new ">LOGIN </a>
          <i class="fa fa-search" ></i>
        
   <!-- <%= link_to "Sign up" , sign_up_path %>
    <%= link_to "log in", log_in_path %>-->
  <% end %>
  </div>
</div>
</div>
</div>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>







 
  <!--  <div class="card bg-dark text-white">
      <div class="card-header">

      <a href="/users/">  <img src="https://corridor.pramati.com/wp-content/uploads/2015/12/logo_corridor_ev3.png" alt="Corridor" class="logo_transparent"/></a>
        
        <div class="cometo">
          <a class="We" href="">HOW WE DO IT</a>
          <a class="Apps" href="/users/#idea">APPS</a>
          <a class="sign_up" href="/users/new">SIGN UP</a>
          <a class="login" href="/sessions/new">LOGIN </a>
          <i class="fa fa-search" ></i>
        </div>
      </div>
    </div> -->





<%= yield %>

<!-- </div> -->
 

<div class="footer">
    <div class="card bg-dark text-white">
      <div class="card-footer"><div class="container" >
      <div class="four columns">
         <div id="text-2" class="widget widget_text">
            <h3>CORRIDOR</h3>
            <div class="textwidget">Helping foster innovation by investing in people and ideas. Combining technology expertise with entrepreneurial skills to help build creative solutions.</div>
         </div>
      </div>
      <div class="four columns">
         <div id="text-7" class="widget widget_text">
            <div class="textwidget">
               <p>&nbsp;</p>
            </div>
         </div>
      </div>
      <div class="four columns">
         <div id="text-9" class="widget widget_text">
            <div class="textwidget">
               <p>&nbsp;</p>
            </div>
         </div>
      </div>
      <div class="four columns">
         <div id="text-10" class="widget widget_text">
            <h3>Contact Us</h3>
            <div class="textwidget">
               <p><a href="http://www.pramati.com/contact/" target="_blank">http://www.pramati.com/contact/</a></p>
            </div>
         </div>
      </div>
   </div>
   </div>
</div>
</div>
  
  </body>
</html>

Training/Corridorr/app/views/users/index.html.erb
 


<!-- 
 <div class="card-body"> -->
<div  class="wpb_row vc_row-fluid full-width-section section  section-no-parallax  stretch   " data-speed="1" style="background-color: #007ea7; padding-top: 50px; padding-bottom: 50px; "><div class="col span_12 color-light left">
  <div class="vc_col-sm-12 wpb_column column_container col no-padding color-dark" style="" data-animation="" data-delay="">
    <div class="wpb_wrapper">
      <h1 class="headline font-inherit fontsize-xxxxl fontweight-500 lh-12 align-center transform-uppercase " style="margin: 0 0 20px 0;">The future of collaborative development is here!</h1>
    </div> 
  </div> 
</div>
</div>


<!-- <div class="row">
    <div class="col-md-6"> -->
      <div class="idea">
      <h4>Ever wanted an App to apply for your leave from the convenience of your phone? Or to make a request for a training? Are you waiting to see if the profile you sent has been shortlisted for an interview? Or do you want to know if your manager has approved your travel request?<br />
Corridor Enterprise Version3 (CEV3) presents you an opportunity to contribute to an App idea; spec out the requirements; collaborate with your fellow developers; interface with the backend using an App SDK or APIs; and, build out stylish, multi-device, responsive web Apps and mobile Apps.
</h4>
</div>
<!-- </div> -->



<!-- <div class="row">
    <div class="col-md-6"> -->
   <div class="single_image wpb_content_element   animate   " data-animation="fade-in-from-bottom" data-delay="20">
    <img width="400" height="449" src="https://corridor.pramati.com/wp-content/uploads/2014/01/letsbuild-card.png" class="attachment-full" alt="" srcset="https://corridor.pramati.com/wp-content/uploads/2014/01/letsbuild-card.png 400w, https://corridor.pramati.com/wp-content/uploads/2014/01/letsbuild-card-267x300.png 267w" sizes="(max-width: 400px) 100vw, 400px" />
      <h4 style="text-align: justify;">Today’s business demands software to be delivered at the speed of consumer apps. Gone are the days where a separate IT team would interface with the end users and stakeholders to draw out the requirements and roll out software. Today’s technology advances empower the business users to be the collaborators in building out software, which evolves with changing needs. This is the era of ‘consumerisation of IT’. And who better to deliver on this than YOU? And what better platform to build out an App than our own WaveMaker platform?</h4>
</div>
    
  <!-- </div>
</div>
</div> -->

Training/Corridorr/app/views/users/new.html.erb
<!-- <div class="col-md-4 col-md-offset-4"> -->
<!--  <div class="card bg-dark text-white">
      <div class="card-header">

      <a href="/users/">  <img src="https://corridor.pramati.com/wp-content/uploads/2015/12/logo_corridor_ev3.png" alt="Corridor" class="logo_transparent"/></a>
        
        <div class="cometo">
          <a class="We" href="">HOW WE DO IT</a>
          <a class="Apps" href="">APPS</a>
          <a class="signup" href="/users/new">SIGN UP</a>
          <a class="login" href="">LOGIN </a>
          <i class="fa fa-search" ></i>
        </div>
      </div>
    </div>
 -->

<div class="error">
<div class="card-body">
<%= form_for @user do |f| %>
<% if @user.errors.any? %>


      <div class="error_messages">
         <h2>Form is invalid</h2>
         <ul>
            <% for message in @user.errors.full_messages %>
            <li><%=message %></li>
            <% end %>
         </ul>
      </div>
      <% end %>
   <!-- s -->
   <div class="sign">
      
         <h1>Sign Up </h1>
        <!--  <p> -->
        	 <div class="field">
            <%= f.label :email %><br/>
            <%= f.text_field :email %>
        </div>
         <!-- </p> -->
         <!-- <p> --> <div class="field">
            <%= f.label :password %><br/>
            <%= f.password_field :password %>
        </div>
         <!-- </p>
         <p> --> <div class="field">
            <%= f.label :password_confirmation %><br/>
            <%= f.password_field :password_confirmation %>
        </div>
         
         <div class="button"><%= f.submit %></div> </div>
         <% end %>
     </div> 
 </div>
  